### PR TITLE
API Endpoint: Get Intel Data

### LINKED ISSUE #5: API Endpoint: Get Intel Data
```
As a user with the intel role for a game
  when I send a GET request to /api/v1/intel
  and I include a JSON body with the token I have been granted for the game
I receive a JSON response including
  a collection of all the cards for the game
  containing the id of the card
  and the type (red/blue/bystander/assassin) of the card
```

#### Request
```http
GET /api/v1/intel
```
```js
{
  "token": "<provided_token>" // e.g. "dG9rZW4="
}
```

#### Successful Response
```http
HTTP/1.1 200 OK
```
```js
{
  "cards": [
    {
      "id": 0, // int card id
      "type": "red" // red, blue, bystander, or assassin
    }, // ... one for each card
  ]
}
```

#### Failed Response
```http
HTTP/1.1 401 Unauthorized
```
```js
{
  "error": "<descriptive_error>"
}
```
The request may fail if:
- The token is not provided
  - Descriptive Error: You must provide your access token
- Unable to find a user with the given token
  - Descriptive Error: Unable to find a user with that token
- The user with the given token does not have intel access
  - Descriptive Error: You are not authorized for this game's secret intel

### PR DESCRIPTION
**Pull request by joequincy**
# Description

Closes #5 

```
As a user with the intel role for a game
  when I send a GET request to /api/v1/intel
  and I include a JSON body with the token I have been granted for the game
I receive a JSON response including
  a collection of all the cards for the game
  containing the id of the card
  and the type (red/blue/bystander/assassin) of the card
```

A necessary part of implementing this endpoint was to actually set up the game. As such, this PR also covers additions to the Game model. An instance of Game can now `establish!` itself. This will:
- grab a random selection of Cards from the database
- choose a starting team
  - assign 9 cards to the starting team
  - assign 8 cards to the other team
  - assign one card as an `assassin`
  - assign the remaining cards as `bystander`s
- assign players to teams at random
  - the first player on each team will be designated as the `intel` player

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other, Please explain:

## Has This Been Tested?

- [ ] No
- [x] Yes
      Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration:
      Tests ensure that games have the correct number of cards, that the correct number have been assigned as red/blue/bystander/assassin, and that intel JSON payload follows the correct format.
- [x] Have any prior tests been changed?
      If so, please explain:
      Rspec documentation discourages validating boolean fields on models, so the validation test for the `chosen` attribute on GameCard has been removed.
      Likewise, the `type` attribute has been renamed to `category`, so the related test has been updated.

# Additional notes:

**Important:** While preparing this, I discovered that ActiveRecord reserves the `type` keyword for models, so I had to add a migration to convert the `type` column to `category`. This does not affect the serialization of the data, but it does mean that running the new migration will be required before additional development.

# Checklist:

- [x] My code has no unused/commented out code
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

File: db/schema.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@
   create_table "game_cards", force: :cascade do |t|
     t.bigint "game_id"
     t.bigint "card_id"
-    t.integer "type"
+    t.integer "category"
```
Comment (rdren0) [inline db/schema.rb]: this will display blue, red, assassin, etc ?

File: app/controllers/api/v1/intel_controller.rb [hunk 2]
```diff
@@ -0,0 +1,34 @@
+class Api::V1::IntelController < Api::V1::ApiController
+  def show
+    if params[:token]
+      player = Player.includes(:user, :game).find_by(token: params[:token])
+      if player&.intel?
+        render json: {
+          cards: serialize_cards(player.game)
+        }
+      elsif player
+        render_error message: "You are not authorized for this game's secret intel"
```
[the remark this answers is not in the document]
Comment (joequincy) [reply app/controllers/api/v1/intel_controller.rb]: This is what will come back if it's able to find a player matching the provided token, but that player doesn't have Intel rights for the game they're participating in.

File: db/schema.rb (hunk 1 above)
Comment (joequincy) [reply db/schema.rb]: Yep, on the DB it's an integer because on the model it's an Enum, so Rails does the grunt work of storing the correct integer to represent the word we actually care about.

The integers stored on the DB are the same as the index of the respective Symbol in the array where we declare the Enum:
https://github.com/code-words/codewords-server/blob/44d23adbf062a11b5ce2ec5f66e6d809645e1cbf/app/models/game_card.rb#L7
