### PR TITLE
API Endpoint: Join game

### LINKED ISSUE #4: API Endpoint: Join Game
```
As a user
  when I send a POST request to /api/v1/games/:invite_code/players
  where :invite_code is a code provided by a friend who has created a game
  and I include a JSON body with the username I wish to use during the game
I receive a JSON response including
  a channel name I can subscribe to for game events
  my approved username
  an access token I can use to communicate with the server about this game
```

#### Request
```http
POST /api/v1/games/:invite_code/players
```
```js
{
  "name": "<desired_username>" // e.g. "Lana"
}
```

#### Successful Response
```http
HTTP/1.1 200 OK
```
```js
{
  "game_channel": "game_x", // e.g. "game_34"
  "name": "Lana",
  "token": "dG9rZW4="
}
```

#### Failed Response
```http
HTTP/1.1 401 Unauthorized
```
```js
{
  "error": "<descriptive error>"
}
```
- The request may fail if:
  - The username is not provided
    - Descriptive Error: You must provide a username
  - The username is already in use for this game
    - Descriptive Error: That username is already taken
  - The invite code is invalid.
    - Descriptive Error: That invite code is invalid
  - The invite code is valid, but the matching game is full.
    - Descriptive Error: That game is already full

### PR DESCRIPTION
**Pull request by joequincy**
# Description
Closes #4 

```
As a user
  when I send a POST request to /api/v1/games/:invite_code/players
  where :invite_code is a code provided by a friend who has created a game
  and I include a JSON body with the username I wish to use during the game
I receive a JSON response including
  a channel name I can subscribe to for game events
  my approved username
  an access token I can use to communicate with the server about this game
```

Once a game has been created, additional players will be provided with an `invite_code` by the player who created the game. They will then send a POST request as defined in the user story above, with the provided invite code inserted where the placeholder is shown in the path. The server will then find the matching Game, create a User in its database, and attach the user to the game as a Player.

As when creating the game, the server will generate a unique token for the new player, and will respond with the Websockets channel name for the game, the player's confirmed name, and their unique token.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other, Please explain:

## Has This Been Tested?

- [ ] No
- [x] Yes
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration:
Added tests covering all paths defined in the referenced Issue.
Added tests for instance methods added to Game model
- [ ] Have any prior tests been changed?
If so, please explain:

# Additional notes:
N/A

# Checklist:

- [x] My code has no unused/commented out code
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -2,5 +2,6 @@
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   scope module: 'api/v1', path: 'api/v1' do
     post '/games', to: 'games#create', as: :create_game
+    post '/games/:invite_code/players', to: 'games#join', as: :join_game
```
Comment (rdren0) [inline config/routes.rb]: Is this for creating players or for starting the game?

Comment (joequincy) [reply config/routes.rb]: This will be for invited players to join an existing game, before the game begins.
